name: Weekly Log Cleanup

on:
  schedule:
    - cron: '0 2 * * 0'  # Every Sunday at 2 AM
  workflow_dispatch:

jobs:
  clean-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run cleanup script
        run: |
          chmod +x cleanup-logs.sh
          ./cleanup-logs.sh

      - name: Commit archived logs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *.tar.gz
          git commit -m "📦 Archived old logs"
          git push || echo "Nothing to commit"
