name: Weekly Log Cleanup

on:
  schedule:
    - cron: '0 2 * * 0'  # Runs every Sunday at 2 AM UTC
  workflow_dispatch:     # Manual trigger for testing

jobs:
  clean-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run cleanup script
        run: |
          chmod +x cleanup-logs.sh
          ./cleanup-logs.sh

      - name: Commit archived logs if any
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if ls *.tar.gz 1> /dev/null 2>&1; then
            echo "📦 Found archive to commit."
            git add *.tar.gz
            git commit -m "📦 Archived old logs"
            git push
          else
            echo "🪹 No archive created — skipping commit."
          fi
